### ISSUE TITLE
Missing static assets

### ISSUE THREAD

**Issue by user9384732902** [controlscanmdr/cyphondock#61]
A colleague followed the setup docs. I had to amend their nginx configs (known issue and understood) but I also had to manually collect django's static assets for both the cyphon logo and /admin static asset. I'm not sure if you would like to add this to the docs or fix elsewhere. Either way this issue may be useful to others.

```
docker exec -it cyphondock_cyphon_1 python manage.py collectstatic
```

**Comment by lhadjchikh** [comment]
Thanks! Usually that step is handled by the entrypoint script when the Docker container starts:

https://github.com/dunbarcyber/cyphon/blob/master/entrypoints/run.sh#L28
https://github.com/dunbarcyber/cyphon/blob/master/Dockerfile#L97

However, if the location of the static assets directory changed in the nginx config, then they would need to be recollected after nginx was restarted. This should happen automatically with a restart of the cyphon container, but the method you gave is obviously quicker, since you don't have to stop the container. I will add a note about this to the docs. Thank you!
